### ISSUE TITLE
    buildToolsVersion '28.0.3'

### ISSUE THREAD

**Issue by goldyonwar** [everhad/AndroidRatingStar#2]
Android resource compilation failed
Output:  /Users/goldyonwar/Documents/job/Merry/HealthMagment/Source/HealthManagement/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1622: error: duplicate value for resource 'attr/cornerRadius' with config ''.
/Users/goldyonwar/Documents/job/Merry/HealthMagment/Source/HealthManagement/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1622: error: resource previously defined here.
/Users/goldyonwar/Documents/job/Merry/HealthMagment/Source/HealthManagement/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1622: error: duplicate value for resource 'attr/strokeWidth' with config ''.
/Users/goldyonwar/Documents/job/Merry/HealthMagment/Source/HealthManagement/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1622: error: resource previously defined here.

Command: /Users/goldyonwar/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/e44fc5973a0519daa717875c1936b60c/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/goldyonwar/Documents/job/Merry/HealthMagment/Source/HealthManagement/app/build/intermediates/res/merged/debug \
        /Users/goldyonwar/Documents/job/Merry/HealthMagment/Source/HealthManagement/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0

**Comment by everhad** [comment]
This is fixed with v1.0.3
